apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: app-env
  envs:
  - ./app-service-a.env
  - ./app-service-b.env

generatorOptions:
  disableNameSuffixHash: true